### ISSUE TITLE
Build on Fedora 34

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#1144]
The nightly Jenkins tests have been failing after the test machine was apparently upgraded to Fedora 34. `scripts/setup.py` reports that:
> Your distribution Fedora version 34 is not supported by this script

@wkozaczuk tried to build on Fedora 34 (with gcc 11), and got a lot of compilation errors. We need to fix those, and update setup.py.

**Comment by nyh** [comment]
@wkozaczuk turns out there are a lot of different problems - from changed header files, changed Boost, and new warnings that find real problems. I fixed already quite a few, but have a few more. When I have everything working, I'll send a patch series.

**Comment by wkozaczuk** [comment]
Fixed by @nyh in a series of commits like ebcc2968c69da90c314e269e0609faa7213a18ef

**Comment by nyh** [comment]
I think the default "scripts/build" (with that Lua shell thing) still doesn't build, but I'll look into that separately, another time.

**Comment by wkozaczuk** [comment]
For whatever reason I am seeing this error:
```
/git-repos/osv/tests/tst-async.cc: In lambda function:
/git-repos/osv/tests/tst-async.cc:145:35: error: ‘sleep_for’ is not a member of ‘std::this_thread’
  145 |                 std::this_thread::sleep_for(10_ms);
      |                                   ^~~~~~~~~
/git-repos/osv/tests/tst-async.cc: In lambda function:
/git-repos/osv/tests/tst-async.cc:236:31: error: ‘sleep_for’ is not a member of ‘std::this_thread’
  236 |             std::this_thread::sleep_for(100_ms);
      |                               ^~~~~~~~~
/git-repos/osv/tests/tst-async.cc: In lambda function:
/git-repos/osv/tests/tst-async.cc:377:31: error: ‘sleep_for’ is not a member of ‘std::this_thread’
  377 |             std::this_thread::sleep_for(10_ms);
      |                               ^~~~~~~~~
/git-repos/osv/tests/tst-async.cc: In lambda function:
/git-repos/osv/tests/tst-async.cc:418:27: error: ‘sleep_for’ is not a member of ‘std::this_thread’
  418 |         std::this_thread::sleep_for(10_ms);
      |                           ^~~~~~~~~
```

**Comment by nyh** [comment]
I don't know how I missed it, but looks like a simple missing include to `<thread>`?

**Comment by wkozaczuk** [comment]
Indeed adding the headed fixes the compilation issue but now we get a runtime error I saw in two cases so far:

```
OSv v0.55.0-282-ga669c61a
eth0: 192.168.122.15
Booted up in 187.93 ms
Cmdline: /tests/tst-async.so
Running 18 test cases...
Unimplemented futex() operation 9

[backtrace]
0x00000000403ed15c <futex(int*, int, int, timespec const*, int*, int)+812>
0x00000000403edbb0 <__syscall+2592>
0x000000004051fda2 <std::__atomic_futex_unsigned_base::_M_futex_wait_until_steady(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)+98>
Test tst-async.so FAILED

OSv v0.55.0-282-ga669c61a
eth0: 192.168.122.15
Booted up in 181.32 ms
Cmdline: /tests/tst-promise.so
Running 1 test case...
Unimplemented futex() operation 9

[backtrace]
0x00000000403ed15c <futex(int*, int, int, timespec const*, int*, int)+812>
0x00000000403edbb0 <__syscall+2592>
0x000000004051fda2 <std::__atomic_futex_unsigned_base::_M_futex_wait_until_steady(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)+98>
Test tst-promise.so FAILED
```

This would be a separate issue I guess.

**Comment by wkozaczuk** [comment]
9 is FUTEX_WAIT_BITSET:
```
FUTEX_WAIT_BITSET (since Linux 2.6.25)
              This operation is like FUTEX_WAIT except that val3 is used
              to provide a 32-bit bit mask to the kernel.  This bit
              mask, in which at least one bit must be set, is stored in
              the kernel-internal state of the waiter.  See the
              description of FUTEX_WAKE_BITSET for further details.

              If timeout is not NULL, the structure it points to
              specifies an absolute timeout for the wait operation.  If
              timeout is NULL, the operation can block indefinitely.

              The uaddr2 argument is ignored.
```

**Comment by nyh** [comment]
I guess it's a new feature that the C++ standard library started to use recently for something :-( I don't know how difficult it is to implement this option... Yes, this deserves a separate issue.
